language: python
dist: trusty
python:
  - '3.6.5'
install:
  - pip install -r requirements.txt
env:
  - DJANGO_SETTINGS_MODULE=ygks.settings.local
script:
  - python manage.py test
  - flake8 domain ygks api --exclude=*/migrations,*settings