# Generated by Django 4.1.1 on 2022-09-28 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='Título')),
                ('sex', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20, verbose_name='Sexo')),
                ('rounds', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('competitor_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('age', models.PositiveIntegerField(default=1, verbose_name='Idade')),
                ('sex', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20, verbose_name='Sexo')),
                ('weight', models.FloatField(default=0.0, verbose_name='Peso (Kg)')),
                ('picture', models.FileField(upload_to='competitor_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.competition')),
            ],
            options={
                'verbose_name': 'Competidor(a)',
                'verbose_name_plural': 'Competidores(as)',
            },
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('round_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lifted_weight', models.FloatField(default=0.0, verbose_name='Peso Levantado (Kg)')),
                ('coefficient', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Coeficiente')),
                ('valid', models.BooleanField(default=True, verbose_name='Round válido?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.competitor')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
    ]
