# Generated by Django 4.1.1 on 2022-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionround',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Coeficiente'),
        ),
    ]
