# Generated by Django 4.0 on 2022-10-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_highlightcompetitionround'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightcompetitionround',
            options={'verbose_name': 'Destaque de Round', 'verbose_name_plural': 'Destaques de Rounds'},
        ),
    ]
